### ISSUE TITLE
FEELnc_codpot

### ISSUE THREAD

**Issue by jdmontenegro** [tderrien/FEELnc#11]
Hi,
I recently installed FEELnc to analyze a transcript assembly of a non-model organism. I tried running the test file and got the following error:

Parsing random forest output: random forest output file './feelnc_codpot_out/candidate_lncRNA.gtf_RF.txt' is empty... exiting

I have installed all the prerequisites and they are working correctly. The first step filtering the transcripts executes correctly, but the second crashes with the above mention error. Since this is the test file you provide with the software and I am following your instruction line by line, do you know what could be causing this error?

Best regards,

Juan Montenegro

**Comment by vwucher** [comment]
Hi,

Have you check manually the 'candidate_lncRNA.gtf_RF.txt' file? Is it really empty? Just to be sure.

if it is empty, can you re-run the coding potential step using the '--keeptmp' option? All temporary will be saved under a 'tmp/' directory inside the output directory './feelnc_codpot_out/'.
And then can you tell us if some of the files in this tmp directory are empty please?
plus, can you give us the full verbose output from FEELnc_codpot.pl?

Thanks in advance,
Best regards,
Valentin

**Comment by jdmontenegro** [comment]
Dear Valentin,

Thank you for your email and sorry for the late reply. I have indeed reran
the command ad I can see that the program is halted after it runs into a
problem with X11:

$ FEELnc_codpot.pl -i candidate_lncRNA.gtf -a annotation_chr38.gtf -b
transcript_biotype=protein_coding -g genome_chr38.fa --mode=shuffle
--keeptmp
Warning: Output directory './feelnc_codpot_out' already exists... files
might be overwritten!
You do not have specified a maximum number mRNAs transcripts for the
training. Use all the annotation, can be long...
You do not have specified a maximum number lncRNA transcripts for the
training. Use all the annotation, can be long...
> Extract ORFs/cDNAs for mRNAs from a GTF file
Parsing file 'annotation_chr38.gtf'...
Parse input file:
[----------------------------------------------------------------------------------------------------]
        Your input GTF file 'annotation_chr38.gtf' contains *254*
transcripts
        Extracting ORFs/cDNAs 254/254...
        Extracted '254' ORF/cDNAs sequences on '254'.
> The lncRNA training file is not set. Get ORFs/cDNAs for lncRNAs by
shuffling mRNA sequences
        Extracting ORFs/cDNAs 756/762...
        Extracted '756' ORF/cDNAs sequences on '762'.
> Extract ORFs/cDNAs for candidates RNAs from a GTF file
Parsing file 'candidate_lncRNA.gtf'...
Parse input file:
[----------------------------------------------------------------------------------------------------]
        Your input GTF file 'candidate_lncRNA.gtf' contains *341*
transcripts
        Extracting ORFs/cDNAs 341/341...
        Extracted '341' ORF/cDNAs sequences on '341'.
> Run random Forest on
'./feelnc_codpot_out//tmp//476_candidate_lncRNA.gtf.test_rna.fa'
        1. Compute the size of each sequence and ORF
        2. Compute the kmer ratio for each kmer and put the output file
name in a list
        3. Compute the kmer score for each kmer size on learning and test
ORF
        4. Merge the score and size files into one file for each type
        5. Make the model on learning sequences and apply it on test
sequences
                Running 10-fold cross-validation on learning
  |======================================================================|
100%
                10-fold cross-validation step is finish. Best threshold
found: '0.5452'.
Error in .External2(C_X11, paste("png::", filename, sep = ""), g$width,  :
  unable to start device PNG
Calls: png
In addition: Warning message:
In png(outROC, h = 800, w = 800) :
  unable to open connection to X11 display ''
Execution halted


I cans ee from the capabilities() of R that png is available and addig the
-type="cairo" to the png commands do not solve this issue. Do you reckon
that is why the file is not being written?

Best regards,

2017-05-17 20:45 GMT+10:00 vwucher <notifications@github.com>:

**Comment by jdmontenegro** [comment]
Hi guys,
I solved the issue. Apparently R did not have the right configuration in my
server. I solved it by changing the png() command to svg() and also
changing the file extensions to .svg. That solved the issues and the
program is running nicely now.

Regards,

Juan Montenegro

2017-05-22 14:02 GMT+10:00 Juan Daniel Montenegro Cabrera <
jdmontenegroc@gmail.com>:

**Comment by tderrien** [comment]
Thank you Juan!

**Comment by enseliy** [comment]
Hi there,
I have the same error "Parsing random forest output: random forest output file './feelnc_codpot_out/candidate_lncRNA.gtf_RF.txt' is empty... exiting" when I run the FEELnc_codpot with my own data like below:
FEELnc_codpot.pl -i candidate_lncRNA.gtf -a annotation.gtf  -g genome.fa --mode=shuffle --keeptmp,
However, it worked well when I tried the same command to the test data, it might be related to my own data? does anyone know what the problem exactly is?
really appreciate it!
Thank you
Yuanxiu Lin

**Comment by vwucher** [comment]
Hi,

Maybe is related to your dataset, can you check if the files between the test data and your files look like the same?

Moreover ,because it is the same error print, I copy/paste my previous answer:

Have you check manually the 'candidate_lncRNA.gtf_RF.txt' file? Is it really empty? Just to be sure.

If it is empty, can you re-run the coding potential step using the '--keeptmp' option? All temporary will be saved under a 'tmp/' directory inside the output directory './feelnc_codpot_out/'.
And then can you tell us if some of the files in this tmp directory are empty please?
Plus, can you give us the full verbose output from FEELnc_codpot.pl?

Thanks in advance,
Best regards,
Valentin

**Comment by enseliy** [comment]
Hi Valentin,
Thanks for the reply, Yes, I checked the files and they look like the test data, plus, when I got this error, I checked the output directory, but there is no file called  'candidate_lncRNA.gtf_RF.txt' only three files are included in the output: lerningData.txt; statstLeran_CrossValidation.txt andTGROC.png. 
If it is because of my own data, the RF.txt is empty, does it mean that my datasets do not include LncRNA?
Thanks
Yuanxiu Lin

**Comment by vwucher** [comment]
Hi,
Ok.
Can you try to re-run the same command using the '--keeptmp' option? It will create a 'tmp' directory inside your output directory will all the files generated by FEELnc. And then can you check inside this folder which files are empty?

Thanks,
Valentin

**Comment by enseliy** [comment]
Hi,
I already re-fun the same command with '--keeptmp', and checked the tmp files, there was no empty file in tmp folder. I have no idea what is wrong with my data, do you have any other suggestions?

Thanks
Yuanxiu Lin

**Comment by vwucher** [comment]
Ok.
Can you check the file ending by '*_learningData.txt', '*.modelCoding.out', '*.modelCoding.out' and '*.modelCoding.out' if there are empty?

Thanks,
Valentin

**Comment by enseliy** [comment]
It might sound not reasonable, but in fact, none of the file you mentioned was empty.

Thanks 
Yuanxiu Lin

**Comment by vwucher** [comment]
OK. Can you give the full output of FEELnc using '--verbosity=2' please?
And have run on the same machine the test files and your files?
Moreover have you check the previous error mention by Juan Montenegro and try the tame thing to correct it?

Valentin

**Comment by enseliy** [comment]
Hi,

I tried using '--verbosity 2' and it gave me the below error:

4. Merge the score and size files into one file for each type

5. Make the model on learning sequences and apply it on test sequences

The threshold for the voting in random forest is not defined. Use 10-fold
cross-validation to determine the best threshold.

env: Rscript: No such file or directory
Parsing random forest output: random forest output file
'./feelnc_codpot_out/allcdstringtie_merged.gtf_RF.txt' is empty... exiting

I ran the test files and my files on the same machine, it works good for
the test files. also I tried the suggestion provided by Juan, it did not
work.

Thank you

Yuanxiu Lin

2017-07-28 17:54 GMT+08:00 vwucher <notifications@github.com>:

**Comment by vwucher** [comment]
Hi,

In the output, the line:
"env: Rscript: No such file or directory"
said that it could not find the "Rscript" executable in your machine. So the R script is not executed and the output file of this script is empty... The strange thing is that apparently the test is working. Can you run the test files with the "--verbosity=2"?
Moreover, are you sure you run it the same way for the test files and your files? There is no change in the computer environment?
The issue is that FEELnc could not find your the "Rscript" command. You can try to run directly in a terminal the "Rscript" command to see if it works. Normally it should be in the "/usr/bin/" directory. If not, the issue come from this. If you can either put the "Rscript" binary in the "/usr/bin/" directory, it could solve the issue. Maybe just a symbolic link could do the job.

Thanks,
Valentin

**Comment by enseliy** [comment]
Hey,

GOOD NEWS! my datafile finally worked, the thing I only did is that I have
changed the run machine from a Mac laptop to a linux server. So i think
maybe there was a memory issue on my mac for my own large datasets.

Thanks for your help! really appreciated that!

Yuanxiu Lin

2017-08-07 16:38 GMT+08:00 vwucher <notifications@github.com>:

**Comment by vwucher** [comment]
Ok, perfect :).
Happy we could help!
Valentin

**Comment by 09151423139** [comment]
Hi. I want to use  server galaxy europe and FEELnc software identify  Long non coding RNA and the software and Error Fatal error: Exit code 1 () receive.Can you help me?

**Comment by 09151423139** [comment]
Hi. I want to use  server galaxy europe and FEELnc software identify  Long non coding RNA and the software and Error Fatal error: Exit code 1 () receive.Can you help me?
