### ISSUE TITLE
Error in Running FEELnc_codpot.pl 

### ISSUE THREAD

**Issue by samreen93** [tderrien/FEELnc#13]
$ perl FEELnc_codpot.pl -i Candidate_LNC.gtf -a Oryza_sativa.gtf -b transcript_biotype=protein_coding -g all.fa --mode=shuffle
Possible precedence issue with control flow operator at /usr/local/share/perl/5.20.2/Bio/DB/IndexedBase.pm line 839.
Subroutine Bio::DB::IndexedBase::_strip_crnl redefined at /usr/lib/x86_64-linux-gnu/perl/5.20/DynaLoader.pm line 210.
You do not have specified a maximum number mRNAs transcripts for the training. Use all the annotation, can be long...
You do not have specified a maximum number lncRNA transcripts for the training. Use all the annotation, can be long...
Error: The environnment variable FEELNCPATH does not reach the 'utils/codpot_randomforest.r' script

**Comment by tderrien** [comment]
Hello,

It seems that the FEELNCPATH variable is not correctly set.
Did you try the "test example" to check that FEELnc installation is ok : 
https://github.com/tderrien/FEELnc#test-with-toy-example

Best,

Thomas

**Comment by samreen93** [comment]
Hello,
         With the test file also i am facing the same problem 

pperl FEELnc_codpot.pl -i candidate_lncRNA.gtf -a annotation_chr38.gtf -b transcript_biotype=protein_coding -g genome_chr38.fa --mode=shuffle

Possible precedence issue with control flow operator at /usr/local/share/perl/5.20.2/Bio/DB/IndexedBase.pm line 839.
Subroutine Bio::DB::IndexedBase::_strip_crnl redefined at /usr/lib/x86_64-linux-gnu/perl/5.20/DynaLoader.pm line 210.
You do not have specified a maximum number mRNAs transcripts for the training. Use all the annotation, can be long...
You do not have specified a maximum number lncRNA transcripts for the training. Use all the annotation, can be long...
Error: The environnment variable FEELNCPATH does not reach the 'utils/codpot_randomforest.r' script

**Comment by tderrien** [comment]
Hello,

I think there are 2 possible issues.
1/ The $FEELNCPATH variable is not correctly set. Did you export the variable such as :
`export FEELNCPATH=/your/path_to/feelnc_directory/`
2/ Which version of bioperl are your using?

Best,

Thomas

**Comment by samreen93** [comment]
Hello Thomas,
                          FEELnc_classifier.pl and FEELnc_filter.pl are working on my system but  i am getting error while running FEELnc_codpot.pl

1) Following steps have been used for FEELNC installation : 
       git clone https://github.com/tderrien/FEELnc.git
       cd FEELnc
      export FEELNCPATH=$/home/priy/Downloads/FEELnc
       export PERL5LIB=$/home/priy/Downloads/FEELnc/lib/:$PERL5LIB
      export PATH=$PATH:$/home/priy/Downloads/FEELnc/scripts/
      export PATH=$PATH:$/home/priy/Downloads/FEELnc/utils/
      export PATH=$PATH:$/home/priy/Downloads/FEELnc/bin/LINUX/


2) The version of Bioperl i am using is : BioPerl-1.007001

**Comment by samreen93** [comment]
Dear Thomas,
                    We are waiting for your reply, for the following query :

 FEELnc_classifier.pl and FEELnc_filter.pl are working on my system but i am getting error while running FEELnc_codpot.pl

    Following steps have been used for FEELNC installation :
    git clone https://github.com/tderrien/FEELnc.git
    cd FEELnc
    export FEELNCPATH=$/home/priy/Downloads/FEELnc
    export PERL5LIB=$/home/priy/Downloads/FEELnc/lib/:$PERL5LIB
    export PATH=$PATH:$/home/priy/Downloads/FEELnc/scripts/
    export PATH=$PATH:$/home/priy/Downloads/FEELnc/utils/
    export PATH=$PATH:$/home/priy/Downloads/FEELnc/bin/LINUX/

    The version of Bioperl i am using is : BioPerl-1.007001

**Comment by vwucher** [comment]
Hello,

Concerning the example you have send to us, it seems that you have put a "$" in front of your home: "$/home/..." for every variable affectation you have made. I think it could lead to a bad definition of the variables.
Could you try running FEELnc by exporting the variable without the "$"?
E.g.:
export FEELNCPATH=/home/priy/Downloads/FEELnc
instead of 
export FEELNCPATH=$/home/priy/Downloads/FEELnc

Moreover, you BioPerl version is BioPerl-1.007001 while we have use FEELnc with the BioPerl-1.6.924 version. Maybe it is an issue.

Thank you and hope the "$" in the variable are the mistake.
Valentin Wucher
