### ISSUE TITLE
Can't call method "close" on an undefined value at.... Running FEELnc_classifier.pl 

### ISSUE THREAD

**Issue by Tichaboni** [tderrien/FEELnc#18]
Hi,
I have the following when running the 'classifier' module 
**(in cleanup) Can't call method "close" on an undefined value at /home/new/perl5/lib/perl5/Bio/DB/SeqFeature/Store/berkeleydb.pm line 1455.** 

It shows the line twice on the terminal and doesn't print the output. How do I get it to run all the way to the end and print the .txt? 

Your help will be appreciated.

**Comment by tderrien** [comment]
Hi Tichaboni,
This message is not an error but a warning which depends on how the berkeleydb.pm has been installed on your system:
https://github.com/tderrien/FEELnc#warnings

It should run normally if you wait for the feelc_filter.pm to be finished.

Best,

Thomas

**Comment by Tichaboni** [comment]
@tderrien @vwucher 

Hi
The module is running with the above warning. It is printing the output text but it has the heading only.

**FEELnc_classifier.pl -i 253candidate_lncRNA.gtf.lncRNA.gtf -a  Gallus_gallusannotation.gtf > 253lncRNA_classes.txt**

**cat 253lncRNA_classes.txt**
isBest	lncRNA_gene	lncRNA_transcript	partnerRNA_gene	partnerRNA_transcript	direction	type	distance	subtype	location

What options should i use?

**Comment by tderrien** [comment]
Hello,

It seems that none of you lncRNAs are in a window of 100kb around transcripts from the gallus annotation.
You could increase the size of the window to search for new interactions further away e.g ( here 1Mb with the option --maxwindow):
`FEELnc_classifier.pl --lncrna=253candidate_lncRNA.gtf.lncRNA.gtf --mrna= Gallus_gallusannotation.gtf --window=100000 --maxwindow=1000000 > 253lncRNA_classes.txt
`
HTH
