### ISSUE TITLE
Error during  FEELnc_codpot.pl  running

### ISSUE THREAD

**Issue by ascendo** [tderrien/FEELnc#19]
Dear FEELnc,

During my running I've got an errors.
It generated same error in Shuffle and intergenic mode.
Do you have any idea?
Thanks!

FEELnc_codpot.pl -i candidate_lncRNA.gtf -a ../../55_pasa/pasa_all2.assemblies.fasta.transdecoder.genome.complete.mrna.fasta -g ../../1_fasta/7_final_chr/iceplant_chr.fasta_sorted --mode=shuffle

 FEELnc_codpot.pl -i candidate_lncRNA.gtf -a ../../55_pasa/pasa_all2.pasa_assemblies.gtf -g ../../1_fasta/7_final_chr/iceplant_chr.fasta_sorted --mode=intergenic

 Your input GTF file 'pasa_all2.pasa_assemblies.gtf' contains *44844* transcripts

------------- EXCEPTION -------------
MSG: Each line of the qual file must be less than 65,536 characters. Line 18 is 35722859 chars.
STACK Bio::DB::IndexedBase::_check_linelength /home/wyim/scratch/bin/FEELnc/lib/Bio/DB/IndexedBase.pm:744
STACK Bio::DB::Fasta::_calculate_offsets /home/wyim/scratch/bin/perl5/perlbrew/perls/perl-5.18.2/lib/site_perl/5.18.2/Bio/DB/Fasta.pm:227
STACK Bio::DB::IndexedBase::_index_files /home/wyim/scratch/bin/FEELnc/lib/Bio/DB/IndexedBase.pm:648
STACK Bio::DB::IndexedBase::index_file /home/wyim/scratch/bin/FEELnc/lib/Bio/DB/IndexedBase.pm:484
STACK Bio::DB::IndexedBase::new /home/wyim/scratch/bin/FEELnc/lib/Bio/DB/IndexedBase.pm:364
STACK ExtractFromFeature::feature2seq /home/wyim/scratch/bin/FEELnc/lib/ExtractFromFeature.pm:399
STACK ExtractCdnaOrf::CreateORFcDNAFromGTF /home/wyim/scratch/bin/FEELnc/lib/ExtractCdnaOrf.pm:303
STACK toplevel /home/wyim/scratch/bin/FEELnc/scripts/FEELnc_codpot.pl:298
-------------------------------------

**Comment by ascendo** [comment]
Reference fasta window size was the problem.

**Comment by xiaoxueye** [comment]
I have the same problem. Have you solved the problem? Can you tell me what to do?
