### ISSUE TITLE
Issues about candidate_lncRNA_classes.txt

### ISSUE THREAD

**Issue by EternalVoice** [tderrien/FEELnc#20]
Hi, @tderrien @vwucher
 I got TWO questions.
1)How can extract FASTA format sequence by final output file-candidate_lncRNA_classes.txt combined with my genome.fa? It seems that the classifier output file only contian distance, how can I get its start_position & end_position?
2) Is there any downstream tools for further analysis? I am stuck in there. I did find lncRNAs using FEELnc, but, so, thanks! But, I have to further analyse these lncRNAs.
  Your reply will be appreciated!

Vaney

**Comment by tderrien** [comment]
Hi Vaney,
Tx for your feedback.
1/ The start and end coordinates of the lncRNAs should be annotated in the .gtf file following the FEELnc_codpotl module. To get the FASTA sequences of transcript sequences annotated in .gtf, there are many tools to do that. If you want, you can use a custom script gtf2fasta.pl available here:
`https://github.com/tderrien/IGDR/blob/master/script/gtf2fasta.pl`
2/ Good question :-) Very difficult to answer depending on your biological questions e.g. finding differentially expressed lncRNAs, conserved lncRNAs, co-expressed lncRNAs:mRNAs...
Best,

Thomas
