### ISSUE TITLE
Issue in the installing of FEELnc

### ISSUE THREAD

**Issue by charleslywang** [tderrien/FEELnc#22]
Dear,
I have a problem on the installing process of FEELnc.
[wkj@localhost FEELnc-master]$ FEELnc_classifier.pl
Can't locate DB_File.pm in @INC (@INC contains: /home/wkj/wkj_software/FEELnc/FEELnc-master//lib/ /home/wkj/wkj_software/FEELnc/FEELnc-master/lib/ /home/wkj/perl5/lib/perl5/x86_64-linux-thread-multi /home/wkj/perl5/lib/perl5 /home/wkj/perl5/lib/perl5/x86_64-linux-thread-multi /home/wkj/perl5/lib/perl5 /home/wkj/perl5/lib/perl5/x86_64-linux-thread-multi /home/wkj/perl5/lib/perl5 /home/wkj/perl5/lib/perl5/x86_64-linux-thread-multi /home/wkj/perl5/lib/perl5 /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at /home/wkj/perl5/lib/perl5/Bio/DB/SeqFeature/Store/LoadHelper.pm line 37.
BEGIN failed--compilation aborted at /home/wkj/perl5/lib/perl5/Bio/DB/SeqFeature/Store/LoadHelper.pm line 37.
Compilation failed in require at /home/wkj/perl5/lib/perl5/Bio/DB/SeqFeature/Store/GFF3Loader.pm line 72.
BEGIN failed--compilation aborted at /home/wkj/perl5/lib/perl5/Bio/DB/SeqFeature/Store/GFF3Loader.pm line 72.
Compilation failed in require at /home/wkj/wkj_software/FEELnc/FEELnc-master//lib//Bio/SeqFeature/database_part.pm line 6.
BEGIN failed--compilation aborted at /home/wkj/wkj_software/FEELnc/FEELnc-master//lib//Bio/SeqFeature/database_part.pm line 6.
Compilation failed in require at /home/wkj/wkj_software/FEELnc/FEELnc-master/scripts/FEELnc_classifier.pl line 12.
BEGIN failed--compilation aborted at /home/wkj/wkj_software/FEELnc/FEELnc-master/scripts/FEELnc_classifier.pl line 12.

I tried a lot of things, but it did not work. What should I do ? 
Please help me! 
Best regards
Kejun 
2018-1-14

**Comment by tderrien** [comment]
Dear Kejun,

First of all, thank you for using FEELnc.
Regarding this issue, it is more likely related to a pb of installation of (bio)perl. The missing file id "DB_File.pm" and should be included your install dir. If it helps it is located here:
"http://search.cpan.org/~pmqs/DB_File-1.840/DB_File.pm"
As indicated in the [FEELnc README](https://github.com/tderrien/FEELnc#installation-and-requirements), did you correctly export the PERL5LIB variable? e.g
`export FEELNCPATH=${PWD}
export PERL5LIB=${FEELNCPATH}/lib/:$PERL5LIB`

Best,

Thomas

**Comment by charleslywang** [comment]
Dear Thomas
Thank your for your reply!
$ pwd
/home/wkj/wkj_software/FEELnc/FEELnc-master
export FEELNCPATH=/home/wkj/wkj_software/FEELnc/FEELnc-master
export PERL5LIB=${FEELNCPATH}/lib/:$PERL5LIB
export PATH=$PATH:${FEELNCPATH}/scripts/
export PATH=$PATH:${FEELNCPATH}/utils/
export PATH=$PATH:${FEELNCPATH}/bin/LINUX/
Is any problem in environment setting ? It is avaliable in the two steps FEELnc_filter.pl and FEELnc_codpot.pl.
After installing "DB_File.pm" according to your suggested website， the new error is comming.
$ FEELnc_classifier.pl
FEELnc_classifier.pl
/usr/bin/perl: symbol lookup error: /home/wkj/perl5/lib/perl5/x86_64-linux-thread-multi/auto/DB_File/DB_File.so: undefined symbol: Perl_xs_handshake

I do not know how to to next.
Best regards
kejun

**Comment by charleslywang** [comment]
another question is: if the lncRNA gtf is not avaiable for the test species, whether the lncRNA fasta file could be used to perform FEELnc_codpot.pl like this, 
 No  annotated  lncRNAs  are  available  but  annotated  lncRNAs  from  a  closest species  (<  ~100  Myr)  are  available:  FEELnc codpot   will  use  them  to  learn  its random forest model.	
FEELnc_codpot.pl -i candidate_model.gtf -a reference_mrna.gtf -l close_species_lncrna.fasta -g genome.fasta 	
Is there any other method to tansfer the bed file to gtf file ?

Thanks a lot!

**Comment by tderrien** [comment]
For the first question, I'm afraid it is more related to your installation of perl/bioperl rather than to FEELnc. 
Maybe this [link](https://www.linuxquestions.org/questions/slackware-14/perl-undefined-symbol-error-since-current-updates-4175417121/) could help but a clean install may probably help.
Best,

Thomas

**Comment by tderrien** [comment]
I'm not sure to correctly understand the second question .
But if you need to convert a bed/gtf to fasta from a closely related species , you could use this home-made script:
https://github.com/tderrien/IGDR/blob/master/script/gtf2fasta.pl

Best,

Thomas

**Comment by charleslywang** [comment]
$ perl -MBio::Root::Version -e 'print $Bio::Root::Version::VERSION,"\n" '
1.007002
Is there any question in installing of bioperl ?
If I installed the "DB_File.pm" you suggested, all three tools FEELnc_filter.pl，FEELnc_codpot.pl and FEELnc_classifier.pl are not available. If I removed the DB_File, FEELnc_filter.pl and FEELnc_codpot.pl are available. 
The second question is: I only have the reference_lncrna.fa and reference_lncRNA.bed file, not  reference_lncrna.gtf in noncode database.  In the second step FEELnc_codpot.pl, how to deal with it? Is there any tool to transfer bed file to gtf file?

**Comment by tderrien** [comment]
The error you mentioned is likely due to a problem of the DB_File package that's why a clean install of the [complete package](http://search.cpan.org/~pmqs/DB_File-1.840/DB_File.pm) could help.
In addition, FEELnc has been tested with BioPerl-1.006924 (not yet 1.007002).

For the second question, many [tools](http://onetipperday.sterding.com/2012/08/convert-bed-to-gtf.html) can convert bed6 or bed12 to gtf.

Let me known if this helps

Thomas

**Comment by charleslywang** [comment]
$ perl -MBio::Root::Version -e 'print $Bio::Root::Version::VERSION,"\n" '
1.007002
Is there any question in installing of bioperl ?
If I installed the "DB_File.pm" you suggested, all three tools FEELnc_filter.pl，FEELnc_codpot.pl and FEELnc_classifier.pl are not available. If I removed the DB_File, FEELnc_filter.pl and FEELnc_codpot.pl are available. 
The second question is: I only have the reference_lncrna.fa and reference_lncRNA.bed file, not  reference_lncrna.gtf in noncode database.  In the second step FEELnc_codpot.pl, how to deal with it? Is there any tool to transfer bed file to gtf file?

**Comment by charleslywang** [comment]
Hi Thomas
sorry later to reply. according to your suggestion, I installed DB file but occurs same problem. I do not known whether the version of BioPerl-1.006924 is right. Now, I could performed the first two steps FEELnc_filter.pl and FEELnc_codpot.pl. Thanks you for your help always.

**Comment by tderrien** [comment]
In case, it could help, I have updated the install section for the issue related to DB::File
See this post : https://github.com/tderrien/FEELnc/issues/10

**Comment by brainfo** [comment]
so how can we install specific version BioPerl??
thx!
