### ISSUE TITLE
Can't locate Parser.pm in @INC

### ISSUE THREAD

**Issue by silvewheat** [tderrien/FEELnc#23]
I install FEELnc by conda, and when I run test command:
FEELnc_filter.pl -i transcript_chr38.gtf -a annotation_chr38.gtf -b transcript_biotype=protein_coding > candidate_lncRNA.gtf
an error occurred:

Can't locate Parser.pm in @INC (you may need to install the Parser module) (@INC contains: /home/CYD/perl5/lib/perl5/5.26.0/x86_64-linux-thread-multi /home/CYD/perl5/lib/perl5/5.26.0 /home/CYD/perl5/lib/perl5/x86_64-linux-thread-multi /home/CYD/perl5/lib/perl5 /home/CYD/perl5/lib/perl5/5.26.0/x86_64-linux-thread-multi /home/CYD/perl5/lib/perl5/5.26.0 /home/CYD/perl5/lib/perl5/x86_64-linux-thread-multi /home/CYD/perl5/lib/perl5 /home/CYD/software/anaconda3/lib/site_perl/5.26.0/x86_64-linux-thread-multi /home/CYD/software/anaconda3/lib/site_perl/5.26.0 /home/CYD/software/anaconda3/lib/5.26.0/x86_64-linux-thread-multi /home/CYD/software/anaconda3/lib/5.26.0 .) at /home/CYD/software/anaconda3/bin/FEELnc_filter.pl line 14.
BEGIN failed--compilation aborted at /home/CYD/software/anaconda3/bin/FEELnc_filter.pl line 14.

what Module should I install?

**Comment by tderrien** [comment]
Hi silvewheat,

Tx for using FEELnc and reporting the issue!
It's probably related to a wrong export of the PERL5LIB variable, could you try to find the Parser.pm module in your FEELnc conda install:
`
find  /home/CYD/software/anaconda3/ -name  "Parser.pm"
`

Then export the PERL5LIB accordingly:
`
export PERL5LIB=$PERL5LIB:/conddir/of/Parser.pm
`

I'll update the README
Best

**Comment by a4free** [comment]
Hi,
I encountered the same problem, but FEELnc prompt：
./FEELnc_filter.pl -h
Can't locate Parallel/ForkManager.pm in @INC
-------------------------------------------------
But when I export PERL5LIB, another error occured:
./FEELnc_filter.pl --man
DB_File.c: loadable library and perl binaries are mismatched (got handshake key 0xdb00080, needed 0xde00080)

What should I do ? Thx ;-)

**Comment by tderrien** [comment]
Hi @a4free,
Indeed, it seems that the 2 perl versions trigger this error.
Using conda install, the perl version 5.22.0 should be installed.
You could try to export PERL5LIB with only 5.22.0 paths, smthg like:
`export PERL5LIB=lib/perl5/site_perl/5.22.0/x86_64-linux-thread-multi:lib/perl5/site_perl/5.22.0`

Let me know if this helps.
Best

**Comment by abretaud** [comment]
Hi,
The conda package is currently broken due to complicated changes in the bioconda architecture.
We're trying to repair it in https://github.com/bioconda/bioconda-recipes/pull/10725

**Comment by sangeeta-25** [comment]
I am facing the same issue mention above. 
Can't locate Parallel/ForkManager.pm in @INC (you may need to install the Parallel::ForkManager module) (@INC contains: /home/bkimathi/miniconda3/pkgs/feelnc-0.1.1-r3.4.1_1/lib/perl5/site_perl/5.22.0/Parser.pm /home/bkimathi/miniconda3/pkgs/feelnc-0.1.1-r3.4.1_2/lib/perl5/site_perl/5.22.0 /home/user/miniconda3/lib/site_perl/5.26.2/x86_64-linux-thread-multi /home/user/miniconda3/lib/site_perl/5.26.2 /home/user/miniconda3/lib/5.26.2/x86_64-linux-thread-multi /home/user/miniconda3/lib/5.26.2 .) at FEELnc_filter.pl line 10.
BEGIN failed--compilation aborted at FEELnc_filter.pl line 10.
I am struggling from the past 4 days. Can you please help me through this. I will be thankful to you.

**Comment by tderrien** [comment]
@sangeeta-25 
Could you tell us if you were using `conda install`?

Tx

**Comment by sangeeta-25** [comment]
I have install perl 5.18 version and export the path still getting this error . please help me through this .

Can't locate Bio/DB/Fasta.pm in @INC (you may need to install the Bio::DB::Fasta module) (@INC contains: /home/csir/Downloads/FEELnc/lib/ /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.30.0 /usr/local/share/perl/5.30.0 /usr/lib/x86_64-linux-gnu/perl5/5.30 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.30 /usr/share/perl/5.30 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at /home/csir/Downloads/FEELnc/lib/StringUtils.pm line 7.
BEGIN failed--compilation aborted at /home/csir/Downloads/FEELnc/lib/StringUtils.pm line 7.
Compilation failed in require at /home/csir/Downloads/FEELnc/lib/ExtractFromHash.pm line 9.
BEGIN failed--compilation aborted at /home/csir/Downloads/FEELnc/lib/ExtractFromHash.pm line 9.
Compilation failed in require at /home/csir/Downloads/FEELnc/lib/Parser.pm line 10.
BEGIN failed--compilation aborted at /home/csir/Downloads/FEELnc/lib/Parser.pm line 10.
Compilation failed in require at FEELnc_filter.pl line 14.
BEGIN failed--compilation aborted at FEELnc_filter.pl line 14.

**Comment by sangeeta-25** [comment]
Perl latest version has been install in the root. please let me know how can i trigger this problem

**Comment by sangeeta-25** [comment]
If i am installing the module separately . then there is a compliation error.

**Comment by sangeeta-25** [comment]
BEGIN failed--compilation aborted at /home/user/perl5/lib/perl5/ExtractFromHash.pm line 8.
Compilation failed in require at FEELnc_filter.pl line 15.

i am getting this error can you please help me through this

**Comment by tderrien** [comment]
Did you correctly export the `$PERL5LIB` path?

and why don't you want to install it via `conda` : https://github.com/tderrien/FEELnc#install-via-conda ?
