### ISSUE TITLE
The number of complete ORF found with computeORF mode is *0* transcripts...

### ISSUE THREAD

**Issue by chklopp** [tderrien/FEELnc#3]
Hi,

When I run FEELnc_codpot.pl (with standard options) on my dataset, I get the following error message : 
The number of complete ORF found with computeORF mode is *0* transcripts... That's not enough to train the program

The feelnc_codpot_out directory is empty.

Is there a way to monitor what computeORF is doing?

Cheers,

Christophe

**Comment by vwucher** [comment]
Hi,

The computeORF function extract different types of OFR depending on the 'orftype' use in option. You can see all the types by looking at the help of FEELnc_codpot.pl:

FEELnc_codpot.pl --help
...
      --learnorftype=1                      Integer [0,1,2,3,4] to specify the type of longest ORF calculate [ default: 1 ] for learning data set.
                                            If the CDS is annotated in the .GTF, then the CDS is considered as the longest ORF, whatever the --orftype value.
                                                    '0': ORF with start and stop codon;
                                                    '1': same as '0' and ORF with only a start codon, take the longest;
                                                    '2': same as '1' but with a stop codon;
                                                    '3': same as '0' and ORF with a start or a stop, take the longest (see '1' and '2');
                                                    '4': same as '3' but if no ORF is found, take the input sequence as ORF.
      --testorftype=1                       Integer [0,1,2,3,4] to specify the type of longest ORF calculate [ default: 1 ] for test data set. See --learnortype description for more informations.
...

By default, the ORF type '1' is use, meaning that the longest ORF between ORF with start and stop codon and the one with only a start codon is chosen.

The message say that on your learning sequences, none have an ORF with start,stop or only start. It seems odd but you can try running FEELnc_codpot.pl with these options: --learnorftype=3 and --testorftype=3. It will take the longest ORF between the one found with start,stop, the one with only start and the one with only stop.

Another thing is to try is to check if on your sequences you get start and/or stop codon. If none is found, then it is normal that FEELnc_codpot.pl didn't find it.

Normally, this execution is thrown if FEELnc_codpot.pl didn't find enough ORF to make a good random forest model. It can only happen during the ORF extraction on your learning sequences, i.e. the mRNA and lncRNA (or intergenic) sequences give in input. If it is not the case, please let us known.

Hope this helps,
The FEELnc developing team

**Comment by tderrien** [comment]
Actually, this issue was due to a corrupted index genome file.
Using high level of verbosity `-v 2`, FEELnc mentioned the pb:
" ExtractFromFeature::feature2seq: your seq chrXXX:1092461-1093257 returns an empty string!...Check 'chr' prefix between your annotation and genome files or remove your genome index file ('Genome.fa.index')..."
The solution is to remove the index genome file and re-run feelnc.
HTH,
 The FEELnc developing team

**Comment by brunohhomem** [comment]
Hi, 
I'm having the same trouble.. I already tried to modify learnorf and tesorf and I had tried with 3 and 4 options.. any suggestions?

> Hi,
> 
> The computeORF function extract different types of OFR depending on the 'orftype' use in option. You can see all the types by looking at the help of FEELnc_codpot.pl:
> 
> FEELnc_codpot.pl --help
> ...
> --learnorftype=1 Integer [0,1,2,3,4] to specify the type of longest ORF calculate [ default: 1 ] for learning data set.
> If the CDS is annotated in the .GTF, then the CDS is considered as the longest ORF, whatever the --orftype value.
> '0': ORF with start and stop codon;
> '1': same as '0' and ORF with only a start codon, take the longest;
> '2': same as '1' but with a stop codon;
> '3': same as '0' and ORF with a start or a stop, take the longest (see '1' and '2');
> '4': same as '3' but if no ORF is found, take the input sequence as ORF.
> --testorftype=1 Integer [0,1,2,3,4] to specify the type of longest ORF calculate [ default: 1 ] for test data set. See --learnortype description for more informations.
> ...
> 
> By default, the ORF type '1' is use, meaning that the longest ORF between ORF with start and stop codon and the one with only a start codon is chosen.
> 
> The message say that on your learning sequences, none have an ORF with start,stop or only start. It seems odd but you can try running FEELnc_codpot.pl with these options: --learnorftype=3 and --testorftype=3. It will take the longest ORF between the one found with start,stop, the one with only start and the one with only stop.
> 
> Another thing is to try is to check if on your sequences you get start and/or stop codon. If none is found, then it is normal that FEELnc_codpot.pl didn't find it.
> 
> Normally, this execution is thrown if FEELnc_codpot.pl didn't find enough ORF to make a good random forest model. It can only happen during the ORF extraction on your learning sequences, i.e. the mRNA and lncRNA (or intergenic) sequences give in input. If it is not the case, please let us known.
> 
> Hope this helps,
> The FEELnc developing team

**Comment by brunohhomem** [comment]
> Actually, this issue was due to a corrupted index genome file.
> Using a high level of verbosity `-v 2`, FEELnc mentioned the pb:
> `" ExtractFromFeature::feature2seq: your seq chrXXX:1092461-1093257 returns an empty string!...Check 'chr' prefix between your annotation and genome files or remove your genome index file ('genome.fa.index')..."`
> The solution is to remove the index genome file and re-run feelnc.
> HTH,
> The FEELnc developing team

I can't remove the genome reference because the pipeline won't run without it.. and I don't know why the program create a "index" file using my reference genome. The following message appears on the screen..:

ExtractFromFeature::feature2seq: your seq chr5:59818889-59819797 returns an empty string!...Check 'chr' prefix between your annotation and genome files or remove your genome index file ('/home/bruno/nayra/Canis_familiaris.fa.**index**')...
