### ISSUE TITLE
Undefined subroutine &Parser::parseGTF when running FEELnc_filter.pl

### ISSUE THREAD

**Issue by mxiang128** [tderrien/FEELnc#30]
Hi,
I ran in to this error while running the sample code:

FEELnc_filter.pl -i transcript_chr38.gtf -a annotation_chr38.gtf -b transcript_biotype=protein_coding
Filtered transcripts will be available in file: 'transcript_chr38.feelncfilter.log'
Undefined subroutine &Parser::parseGTF called at /home/ke.zhang/Programs/miniconda3/envs/conda_env/bin/FEELnc_filter.pl line 87.

I was able to see the help page when running the script without any arguments.
Could anyone help me identify the problem? Thank you.

**Comment by vwucher** [comment]
Hi,

Apparently this is related to the fact that 'perl' can not find the parseGTF function.
Do you install FEELnc with 'conda' or by taking the version from 'github'?
And did you try to export the global variables (see below)?
```
export FEELNCPATH=${PWD}
export PERL5LIB=$PERL5LIB:${FEELNCPATH}/lib/ #order is important to avoid &Bio::DB::IndexedBase::_strip_crnl error with bioperl >=v1.7

export PATH=$PATH:${FEELNCPATH}/scripts/
export PATH=$PATH:${FEELNCPATH}/utils/
```

Thanks,
Valentin

**Comment by mxiang128** [comment]
Hi Valentin,
The issue was due to having conda installed to multiple directories and I was able to resolve it by deleting the path which did not contain the libraries.
Thank you,
Menglan

**Comment by vwucher** [comment]
Hi,

It's nice that you found the solution!

Valentin
