### ISSUE TITLE
merged.gtf file not working with FEELnc

### ISSUE THREAD

**Issue by Tichaboni** [tderrien/FEELnc#32]
Hi @tderrien @vwucher @flegeai 
I have used your program with individual gtf files generated using cufflinks and it is working alright. I have used cuffmerge to combine different gtf files (technical replicates) but the merged.gtf file does not produce an output in the filter module. It creates an empty candidate_lncRNA.gtf file. 

`head merged.gtf`
```
chr1	Cufflinks	exon	70097	70162	.	+	.	gene_id "XLOC_000001"; transcript_id "TCONS_00000001"; exon_number "1"; gene_name "HCLS1"; oId "NM_001031401"; nearest_ref "NM_001031401"; class_code "="; tss_id "TSS1"; p_id "P1";
chr1	Cufflinks	exon	72159	72242	.	+	.	gene_id "XLOC_000001"; transcript_id "TCONS_00000001"; exon_number "2"; gene_name "HCLS1"; oId "NM_001031401"; nearest_ref "NM_001031401"; class_code "="; tss_id "TSS1"; p_id "P1";
chr1	Cufflinks	exon	73496	73569	.	+	.	gene_id "XLOC_000001"; transcript_id "TCONS_00000001"; exon_number "3"; gene_name "HCLS1"; oId "NM_001031401"; nearest_ref "NM_001031401"; class_code "="; tss_id "TSS1"; p_id "P1";
chr1	Cufflinks	exon	73697	73826	.	+	.	gene_id "XLOC_000001"; transcript_id "TCONS_00000001"; exon_number "4"; gene_name "HCLS1"; oId "NM_001031401"; nearest_ref "NM_001031401"; class_code "="; tss_id "TSS1"; p_id "P1";
```
.....truncated..
What do I need to do to proceed with the merged file?

Thanks.

**Comment by tderrien** [comment]
Hi @Tichaboni ,

Sorry for the late reply. Did you manage to use your merged file within FEELnc?
If no, could you tell us the parameters used for the filter module?
Best

Thomas
