### ISSUE TITLE
codpot performance 

### ISSUE THREAD

**Issue by Simon602** [tderrien/FEELnc#33]
Dear All 

 in the codpot.pl, I used the lncRNAs sequence to train the algorithm but the in the graph ROC curves there is a shifting in mRNA specificity curves when I launched it with -l flag to train algorithm with lncRNAs fasta sequence compare to  --mode=shuffle or intergenic flags,  why coding probability for mRNA specificity curve started at 0.2 ? according to the curves which method is better, training with lncRNA.fasta or --mode=shuffle ?
Thanks 
![candidate_lncrna_traning_mode groc](https://user-images.githubusercontent.com/45264252/48907054-4c586c80-ee5e-11e8-8eca-bd1715c9b21a.png)
![codpot_shuffle_flag](https://user-images.githubusercontent.com/45264252/48907067-55493e00-ee5e-11e8-9110-d2b41681f3e4.png)

**Comment by tderrien** [comment]
HI @Simon602 ,

Regarding your first question, the mRNA specificity actually starts at ~0  but the y-axis limits is zoomed to 0,5->1.

> according to the curves which method is better, training with lncRNA.fasta or --mode=shuffle ?

It really depends on the confidence you have in your lncRNA training file. If your are not sure about their robustness, you can indeed use the `shuffle` method (which performs better than `intergenic` in our analysis)
Bw,

Thomas
