### ISSUE TITLE
Error with FEELnc_codpot

### ISSUE THREAD

**Issue by iramai** [tderrien/FEELnc#34]
Hi!
I am new using FEELnc and I have an error with the second step of the tool. Here it is the error I have received it when running it:

Possible precedence issue with control flow operator at /software/anaconda2/lib/site_perl/5.26.2/Bio/DB/IndexedBase.pm line 845.
You do not have specified a maximum number mRNAs transcripts for the training. Use all the annotation, can be long...
You do not have specified a maximum number lncRNA transcripts for the training. Use all the annotation, can be long...
Error: You should set the environnment variable FEELNCPATH to the dir of installation
export FEELNCPATH=my_dir_of_install/

I know that a lot of people have submited similar errors, but me and the bioinformatic of my time are incapable to solve it, so we need help!

Thanks in advance!

Iraia

**Comment by iramai** [comment]
Sorry for the post, finally we made it work... I did not understand what was the final problem to install it properly, but know it works.
The thing is that I run it, and when I looked to the output files, I don't have any plot file. Not the groc curve neither the VarImpPlot. 
Can you tell me why is this happening? do I need to add an option to have the graphs?

Thanks again,

Iraia

**Comment by tderrien** [comment]
Hi Iraia,

Glad you managed to export the FEELNCPATH regarding your 1st post.
For the 2nd, do you have the .txt/.fa files in the results directory?
An could copy/paste the output of FEELnc_codpot program?
I'm afraid, it's more an issue related to your R installation.
Best

Thomas

**Comment by iramai** [comment]
Thank Thomas, for answering my questions!

Yes,  I also think that there is a problem with ROCR test package. But the bioinformatic of my team is now on holiday so, I was wondering if it is possible to have that roc curve graph from R running it with another pipeline with any output .txt file from the codpot tool (_RF_statsLearn_CrossValidation.txt file or something like that).

Another question I have is that once I have run all the steps of the FEELnc tool, I don't know how to work with the results... excuse my ignorance.

For example, after using FEELnc_filter.pl (first step), are this results all the lncRNAs that match with my RNA-seq samples? To know the name of them do I need to intersect with for example a lncRNA database (lncRBase, http://bicresources.jcbose.ac.in/zhumur/lncrbase/) ?

Or do I need to performe the next two steps and only work with the las output (after FEELnc_classifier.pl)? I am wrong thinking that they only are new or unknown lncRNAs?

Finally is there a tool or something to match each lncRNA with the partner gene or something like a gene ontology site to work with lncRNAs? I'm not sure if I consider the "1" in isBest column and annotate the lncRNA to the nearest gene I am doing it properly.

Sorry for all that questions that are not based on errors, and are full of conceptual problems.

I would be very grateful if you could help me,

Thanks in advance,

Iraia

**Comment by tderrien** [comment]
>  I was wondering if it is possible to have that roc curve graph from R running it with another pipeline with any output .txt file from the codpot tool (_RF_statsLearn_CrossValidation.txt file or something like that).

Actually, the 2-graph ROC curve is just a visual representation of the _RF_statsLearn_CrossValidation.txt file.

For the other questions, it really depends on what you were the input files and options you used for running FEELnc. 
After the 1st step (filter.pl), you end up with a list of transcript that are a combination of mRNAs and lncRNAs. Only the 2nd step (codpot.pl) will annotate these candidate transcripts as mRNAs and lncRNAs.
If you want to compare the list of putative lncRNAs annotated by FEELnc to known databases, you could use program like [bedtools](https://github.com/arq5x/bedtools2) to compare genomic coordinates.

Finally, regarding your question:

> Finally is there a tool or something to match each lncRNA with the partner gene or something like a gene ontology site to work with lncRNAs? I'm not sure if I consider the "1" in isBest column and annotate the lncRNA to the nearest gene I am doing it properly.

Usually, people tend to use closest mRNAs (which is annotated by the "1" is Best) in the 3rd classifier step to try to functionally predict interaction bw newly annotated lncRNAs and closest mRNAs. 

HTH

Thomas
