### ISSUE TITLE
 'MSG: Failed validation of sequence '1'. Invalid characters"  

### ISSUE THREAD

**Issue by tderrien** [tderrien/FEELnc#35]
I came to this page because I had the error 'MSG: Failed validation of sequence '1'. Invalid characters"  which is in this thread. There was no problem with my files or indices. I **introduced line breaks** into the FASTA file and it solved the problem. I realized this when I isolated the sequence on which it was bombing and ran the program again only on that sequence.  Perl tells me that 'MSG: Each line of the file must be less than 65,536 characters. Line 2 is 721461 chars.'

_Originally posted by @ginac in https://github.com/tderrien/FEELnc/issues/10#issuecomment-454741196_

**Comment by tderrien** [comment]
Thank you for reporting this issue (which I've just edited).
I think it is more related to Bioperl:SeqIO issue which does not like big one-line fasta (>65,536 nucleotides) and not directly FEELnc.

**Comment by arslan9732** [comment]
This error is due to a single-line multi-FASTA file. I would recommend first run fold command on the reference fasta file if it is not a multilined fasta.
```
fold single_line.fasta > multiline fasta
``` 
It will resolve both of the following errors:
```
------------- EXCEPTION: Bio::Root::Exception -------------
MSG: Failed validation of sequence '1'. Invalid characters were: >
```
```
------------- EXCEPTION: Bio::Root::Exception -------------
MSG: Each line of the qual file must be less than 65,536 characters. Line 2 is 32649329 chars.
```

**Comment by tderrien** [comment]
Thank you @arslan9732 for the nice trick with `fold`.
