### ISSUE TITLE
Error while running FEELnc

### ISSUE THREAD

**Issue by priyankajain31784** [tderrien/FEELnc#41]
tkm@tkm:~/Software/FEELnc/scripts$ ./FEELnc_filter.pl 
Can't locate Parser.pm in @INC (you may need to install the Parser module) (@INC contains: %LIB $/home/tkm/Software/FEELnc/lib/ $/home/tkm/Software/FEELnc/lib/ /home/tkm/Downloads/FEELnc-master/lib/Parser.pm /home/tkm/.cpan/build/Pod-Usage-1.69-0/t/inc/Pod/Parser.pm /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.22.1 /usr/local/share/perl/5.22.1 /usr/lib/x86_64-linux-gnu/perl5/5.22 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.22 /usr/share/perl/5.22 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base .) at ./FEELnc_filter.pl line 14.
BEGIN failed--compilation aborted at ./FEELnc_filter.pl line 14.

tkm@tkm:~/Software/FEELnc/scripts$ ./FEELnc_codpot.pl 
Can't locate Parser.pm in @INC (you may need to install the Parser module) (@INC contains: /home/tkm/Software/FEELnc/scripts/_Inline/lib %LIB $/home/tkm/Software/FEELnc/lib/ $/home/tkm/Software/FEELnc/lib/ /home/tkm/Downloads/FEELnc-master/lib/Parser.pm /home/tkm/.cpan/build/Pod-Usage-1.69-0/t/inc/Pod/Parser.pm /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.22.1 /usr/local/share/perl/5.22.1 /usr/lib/x86_64-linux-gnu/perl5/5.22 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.22 /usr/share/perl/5.22 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base .) at ./FEELnc_codpot.pl line 20.
BEGIN failed--compilation aborted at ./FEELnc_codpot.pl line 20.

tkm@tkm:~/Software/FEELnc/scripts$ ./FEELnc_classifier.pl 
Can't locate Bio/SeqFeature/database_part.pm in @INC (you may need to install the Bio::SeqFeature::database_part module) (@INC contains: %LIB $/home/tkm/Software/FEELnc/lib/ $/home/tkm/Software/FEELnc/lib/ /home/tkm/Downloads/FEELnc-master/lib/Parser.pm /home/tkm/.cpan/build/Pod-Usage-1.69-0/t/inc/Pod/Parser.pm /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.22.1 /usr/local/share/perl/5.22.1 /usr/lib/x86_64-linux-gnu/perl5/5.22 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.22 /usr/share/perl/5.22 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base .) at ./FEELnc_classifier.pl line 12.
BEGIN failed--compilation aborted at ./FEELnc_classifier.pl line 12.

**Comment by tderrien** [comment]
Hello,

Sorry for the delay.
It seems the programs cannot find the correct `PATH`. Did you export them as mentioned  in the [Install section](https://github.com/tderrien/FEELnc#installation) ?
```
export FEELNCPATH=${PWD}
export PERL5LIB=$PERL5LIB:${FEELNCPATH}/lib/
export PATH=$PATH:${FEELNCPATH}/scripts/
export PATH=$PATH:${FEELNCPATH}/utils/
```

Best,

Thomas

**Comment by kbohon2011** [comment]
I installed on my linux server according to the instructions exactly in the Install section and am having the same error. FEELnc package cannot find the path for the perl scripts on test it seems.

**Comment by tderrien** [comment]
Hello @kbohon2011,

Did you `cd` into the FEELnc directory before exporting the `PATH`?
*e.g.*  
```
cd FEELnc
export FEELNCPATH=${PWD}
export PERL5LIB=$PERL5LIB:${FEELNCPATH}/lib/ 
export PATH=$PATH:${FEELNCPATH}/scripts/
export PATH=$PATH:${FEELNCPATH}/utils/
```

Otherwise, you could also try the [conda installation](https://github.com/tderrien/FEELnc#install-via-conda).

Let me know how is it going.


Best,

Thomas

**Comment by kbohon2011** [comment]
Thomas,

Unfortunately, I'm still unable to use this program.

Latest roadblock: FEELnc_filter.pl -i transcript_chr38.gtf -a
annotation_chr38.gtf -b transcript_biotype=protein_coding >
candidate_lncRNA.gtf
Can't locate Parallel/ForkManager.pm in @INC (@INC contains:
/usr/local/lib/perl5/ /usr/local/lib64/perl5 /usr/local/share/perl5
/usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5
/usr/share/perl5 .) at
/media/set2iscsi/Kori_Corn_Diss/FEELnc/scripts/FEELnc_filter.pl line 10.
BEGIN failed--compilation aborted at
/media/set2iscsi/Kori_Corn_Diss/FEELnc/scripts/FEELnc_filter.pl line 10.

**Comment by tderrien** [comment]
Tx for the reply @kbohon2011.
Could you paste the output of this command:
```
echo $FEELNCPATH, echo $PATH
```
An did you try the `conda install feelnc `?
