### ISSUE TITLE
Installion

### ISSUE THREAD

**Issue by tan5251** [tderrien/FEELnc#46]
I thinks the installation is very diffcult for a  linux fresh. I cannot install it by conda and git clone. Can you make a more easier installation way?

**Comment by vwucher** [comment]
Hi @tan5251,

Unfortunately, we are not planning to provide another way of installing FEELnc. Can you tell us the issue with git clone and conda?
For the conda installation, did you tried to apply the solution there? https://github.com/tderrien/FEELnc/issues/43
For the github installation, you should be able to install bioperl and R from your linux distribution and then normally FEELnc will be able to run.

Tell us the issue and we will try to help you.

Have a nice day,
Valentin

**Comment by tan5251** [comment]
Thanks for your reply. I have successfully run the program by using conda installation. 

Best regards,
Tan
