### ISSUE TITLE
Question about lncRNA transcript classification

### ISSUE THREAD

**Issue by kasra2018** [tderrien/FEELnc#48]
Hello,

I'm studying LncRNA and used the noncode database (http://www.noncode.org) for my own study. Unfortunately, there is only a fasta file in this database and no GTF file.
While to classify lncRNAs based on the following command, a GTF file is required

FEELnc_classifier.pl               -i lncRNA.gtf                     -a ref_annotation.GTF                     > lncRNA_classes.txt

so, How can I use the fasta file of this database to create lncRNA classification?
Can I add an option in feelnc software to use the fasta file?

**Comment by tderrien** [comment]
Hi,

Thank you for posting here ;-)

One quick solution would be to align the fasta file on the reference genome using a splice-aware mapper such as  [minimap2](https://github.com/lh3/minimap2) or [STAR](https://github.com/alexdobin/STAR).

Hope this helps.
