### ISSUE TITLE
Possible precedence issue with control flow operator at

### ISSUE THREAD

**Issue by hmkim** [tderrien/FEELnc#5]
[a5a8f7582a886432041ce0a4001066.zip](https://github.com/tderrien/FEELnc/files/392808/a5a8f7582a886432041ce0a4001066.zip)

1. Extract attached file.
2. run with .command in the directory.

Possible precedence issue with control flow operator at /BiO/BioTools/miniconda3/lib/perl5/site_perl/5.22.0/Bio/DB/IndexedBase.pm line 791.
- Error: no lncRNA sequences have been given in input and the lncRNA sequences simulation mode have not been set. If no lncRNA, please choose a mode between 'shuffle' or 'intergenic'

Usage:
    FEELnc_codpot.pl -i transcripts.GTF -a known_mRNA.GTF -g genome.FA -l
    known_lnc.GTF [options...]

Can you check this, please?

**Comment by vwucher** [comment]
Hello,

It seems that in the .command.sh an option is missing.
In the latest version of FEELnc, the user need to specify a mode of simulation/extraction of lncRNA sequences (option '_--mode_', see the help of FEELnc), either by extracting intergenic sequences '_--mode=intergenic_', either by shuffling mRNA sequences '_--mode=shuffle_'.
You need to add to your .command.sh one of the two options.

We hope this will resolve your issue, please let us known if it work,
FEELnc team

**Comment by hmkim** [comment]
Thanks, I resolve my issue with your comment.
