### ISSUE TITLE
transcript_biotype

### ISSUE THREAD

**Issue by kevinmuret** [tderrien/FEELnc#52]
Salut Thomas,
Juste pour te prévenir que dans la version GENCODE 39 de l'annotation humaine de décembre dernier, la notion de gene_biotype et transcript_biotype est devenue gene_type et transcript_type. De souvenir, FEELnc récupère ce champ. Peut-être que cela génèrera du coup des soucis ? 
A bientôt ;)
Kévin Muret

**Comment by tderrien** [comment]
Tx pour l'info @kevinmuret !
A bientôt!

**Comment by tderrien** [comment]
Après verification, on uniformise le tx {bio}type dans le `Parser.pm`!
Merci again!
++
