### ISSUE TITLE
FEELnc_filter.pl -b transcript_biotype=protein_coding

### ISSUE THREAD

**Issue by TluckDucky** [tderrien/FEELnc#54]
Hello there,

I'm running the FEELnc_filter module in two approaches, as follows:

`-i taco-new-assembly.gtf -a gencode.v40.primary_assembly.annotation.gtf -b transcript_biotype=protein_coding --monoex=0 -p 16 -o FEELnc_filter-1stStranded.log > 1st-strandedTFBfiltered.gtf &`

and

`-i taco-new-assembly.gtf -a gencode.v40.primary_assembly.annotation.gtf --monoex=0 -p 16 -o FEELnc_filter-1stStranded.log > 1st-strandedTFBfiltered.gtf &`

When I checked the results, I got the same number of transcripts (35.395) , and I was expecting to get a larger number using the second approach since I haven't provided the option `-b transcript_biotype=protein_coding`, why is that? I read some stuff here and on internet, studied my data but couldn't figure it out. 

May you help me, please?

Thanks in advance

**Comment by vwucher** [comment]
Hi,

Sorry for the delay of the answer.
GENCODE changes their name for the `biotype`. It is now called `type`.  Did you try running the command `-b transcript_type=protein_coding`?

Hope this help!
Valentin
