### ISSUE TITLE
Functional analysis om MSTRG genes found by feelnc

### ISSUE THREAD

**Issue by JasminJ1** [tderrien/FEELnc#55]
Hi,

I'm trying to perform Functional analysis om MSTRG genes found by feelnc. Is it possible to find the function of novel genes like this?

Thanks for your help!

**Comment by tderrien** [comment]
Hi,
It is not directly feasible since MSTRG are (by definition) novel genes without any functional information.
One proxy could be to use mRNA partner as given by `FEELnc_classifier` and use the functional information of these associated mRNAs.
Hope this helps.

**Comment by JasminJ1** [comment]
Thanks for the quick response! Just curious, if the novel mRNA has a MSTRG label also, would it not be possible to perform Functional analysis?

**Comment by tderrien** [comment]
Since MSTRG do not possess have Functional informations, it is not directly possible to make Functional analysis.
