### ISSUE TITLE
Can't locate object method "contains" via package "Bio::SeqFeature::Generic" 

### ISSUE THREAD

**Issue by ProfessionalFarmer** [tderrien/FEELnc#6]
Hi, I have try to run on test data. FEELnc_filter.pl and FEELnc_codpot.pl. But FEELnc_classifier.pl encountered a error.

Command:
FEELnc_classifier.pl -i feelnc_codpot_out/candidate_lncRNA.gtf.lncRNA.gtf -a annotation_chr38.gtf > candidate_lncRNA_classes.txt

Error: 
window : 10000 - max window : 100000 - lncrna : feelnc_codpot_out/candidate_lncRNA.gtf.lncRNA.gtf - mrna : annotation_chr38.gtf - biotype: 0
**Can't locate object method "contains" via package "Bio::SeqFeature::Generic" at /usr/local/share/perl/5.18.2/Bio/SeqFeature/Generic.pm line 865, <GEN0> line 1114.**

It seems that script can load Bio::SeqFeature::Generic, but can not locate method contains. The error line:

 864     } else {
 865         if ( !$self->contains($feat) ) {
 866             $self->throw("$feat is not contained within parent feature, and expansion is not valid");
 867         }
 868     }

$ perl -MBio::Perl -le 'print Bio::Perl->VERSION;'
1.006924

$ perl -version
This is perl 5, version 18, subversion 2 (v5.18.2) built for x86_64-linux-gnu-thread-multi
(with 41 registered patches, see perl -V for more detail)

How can I fix this error?  Could you have a check.

Many thanks.

**Comment by ProfessionalFarmer** [comment]
Sorry about this issue.
I clean up my PERL5LIB variable. It works fine. So please close this issue.

**Comment by vwucher** [comment]
No problem.
Happy this work fine !

**Comment by ProfessionalFarmer** [comment]
Hi, is Parralell::ForkManager a spelling mistake?  
I think Paralell::ForkManager is the right word in requirements section ([https://github.com/tderrien/FEELnc#requirements](https://github.com/tderrien/FEELnc#requirements)).

**Comment by tderrien** [comment]
Hello,

Indeed, good catch!
Best

Thomas
