### ISSUE TITLE
error when running the classifier

### ISSUE THREAD

**Issue by jesgomez** [tderrien/FEELnc#8]
Hi, 
I am getting the following error when trying to run the classifier: 
Argument "lncrna:" isn't numeric in numeric comparison (<=>) at /apps/BIOPERL/1.6.1/lib/perl5/Bio/DB/SeqFeature/Store/berkeleydb3.pm line 89.
Any idea of how can I solve that? 
Thank you in advance,
Jèssica

**Comment by tderrien** [comment]
Hello Jèssica,

I suspect a wrong format of one of the 2 input files.
Could you please send me a "head" of the 2 files?
Thank you
