### ISSUE TITLE
error calculating the coding potential

### ISSUE THREAD

**Issue by profkaramba** [tderrien/FEELnc#9]
Hi Thomas
Joao from CRG here, I hope everything is fine with you!

I'm trying your tool but I get an error when running "FEELnc_codpot.pl"

"Use of uninitialized value $fileno in array element at /usr/local/share/perl5/Bio/DB/IndexedBase.pm line 1022."

We just had a system upgrade, maybe incompatible packages?

thanks
João

**Comment by profkaramba** [comment]
We have Bioperl version 1.007001

**Comment by vwucher** [comment]
Hi Joao,

Did you use the last version of FEELnc (update Monday 30 January)?
We now use a modified version of the IndexedBase.pm file. To follow this change, the order for exporting variables has change:

Export PERL5LIB and FEELNCPATH variables
export FEELNCPATH=${PWD}
**export PERL5LIB=${FEELNCPATH}/lib/:$PERL5LIB**

export PATH=$PATH:${FEELNCPATH}/scripts/
export PATH=$PATH:${FEELNCPATH}/utils/ 

Please, let us known if this solve the issue or if you have any trouble.

Bye,
Valentin Wucher

**Comment by tderrien** [comment]
Hola Joao,

Good to have some news from you :)
If the Valentin' solution did not work, you could try to remove the genome index file that was created by FEELnc_codpot.pl with the older Bioperl version.
Basically, the index file is your genome file with the suffix "index" (e.g "genome_file.fa.index").
Then, you relaunch FEELnc_codpot.pl and it will automatically create the new genome index file with the  correct bioperl version.

Let me know if this solved the issue.

Fins aviat

**Comment by profkaramba** [comment]
Thanks Valentin and Thomas,
I was using the correct version already but deleting the index solved the problem!

Fins aviat ;)

**Comment by tderrien** [comment]
Perfecto!
